export enum QueryKey {
    LOGIN = "/auth/login",
    PAGES = "/pages",
    IMAGES = '/upload/images',
    FILES = '/upload/files',
    HERO_SECTIONS = "/hero-sections",
    FORMS = "/forms",
    FORM_SUBMISSION = '/form-submissions',
    FAQS = "/faqs",
    METADATA = "/metadata",
    COURSES = "/courses",
    BLOGS = "/blogs",
    BLOG_CATEGORIES = "/blog-categories",
    COMPANY_INFO = "/company-info",
    JOBS = "/jobs",
    GENERAL_SETTING="/general-setting",
    PRIVACYPOLICY = '/general-setting/privacy-policy',
    TERMANDCONDITION = '/general-setting/terms-and-condition',
    FORGETPASSWORD = '/auth/forgetPassword',
    CHANGEPASSWORD = '/auth/changePassword',
    GALLERY_CATEGORIES="gallery-categories",
    GALLERY_IMAGES = "/gallery-images",
    HEADER = "/header",
    FOOTER = "/footer"
}